# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 07:49
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import member.file_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(blank=True, max_length=150, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='child_name')),
                ('child_birth_date', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Constitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('content', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now_add=True)),
                ('docfile', models.FileField(blank=True, help_text='Document File', null=True, upload_to='documents/%Y/%m/%d/', validators=[member.file_validators.file_size])),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=31, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('description', models.TextField()),
                ('created', models.DateField(auto_now_add=True, verbose_name='date created')),
            ],
            options={
                'ordering': ['name'],
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='ExecMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee_position', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='committee_position')),
                ('rank', models.IntegerField(blank=True)),
                ('member_start_date', models.DateField(blank=True)),
                ('member_end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, height_field='height', help_text='Event Picture', null=True, upload_to='events/%Y/%m/%d/', validators=[member.file_validators.file_size], width_field='width')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Event')),
            ],
            options={
                'verbose_name': 'gallery event',
                'get_latest_by': 'pub_date',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('name_in_bangla', models.CharField(max_length=250)),
                ('nick_name', models.CharField(max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(max_length=5)),
                ('present_address', models.CharField(blank=True, max_length=250)),
                ('permanent_address', models.CharField(blank=True, max_length=250)),
                ('tele_land', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('tele_cell', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('photo', django_resized.forms.ResizedImageField(blank=True, help_text='Person Picture', null=True, upload_to='persons/%Y/%m/%d/', validators=[member.file_validators.file_size])),
                ('admission_session', models.CharField(max_length=10)),
                ('degree_obtained', models.CharField(choices=[('B.Sc(Hons)', 'B.Sc(Hons)'), ('M.Sc', 'M.Sc'), ('M.S', 'M.S'), ('M.Phil', 'M.Phil'), ('PhD', 'PhD')], default='M.Sc', max_length=9)),
                ('passing_year', models.IntegerField(choices=[(1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016)], default=2016, verbose_name='year')),
                ('profession', models.CharField(max_length=25)),
                ('Designation', models.CharField(blank=True, max_length=40, null=True)),
                ('organization', models.CharField(blank=True, max_length=75)),
                ('official_address', models.CharField(blank=True, max_length=250)),
                ('office_phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('office_mobile', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('office_email', models.EmailField(blank=True, max_length=70, null=True)),
                ('office_fax', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('website', models.URLField(blank=True, max_length=250)),
                ('payment_number', models.CharField(blank=True, max_length=60, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=30, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=50, null=True)),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('is_married', models.BooleanField(default=True)),
                ('national_id_no', models.IntegerField(unique=True)),
                ('passport_no', models.CharField(blank=True, max_length=15, null=True)),
                ('spouse_name', models.CharField(blank=True, max_length=200, null=True)),
                ('spouse_blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('image_height', models.PositiveIntegerField(blank=True, default='100', editable=False, null=True)),
                ('image_width', models.PositiveIntegerField(blank=True, default='100', editable=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Membership')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_persons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='execmember',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Person'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, to='member.Tag'),
        ),
        migrations.AddField(
            model_name='children',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Person'),
        ),
        migrations.AlterUniqueTogether(
            name='gallery',
            unique_together=set([('slug', 'event')]),
        ),
    ]
