# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 06:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='execmember',
            name='committe_period',
            field=models.CharField(default=-2, max_length=9, validators=[django.core.validators.RegexValidator(message='Period format yyyy-yyyy not comply.', regex='^(\\d{4}-(\\d{2}|\\d{4}))$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(db_index=True, max_length=65, unique=True),
        ),
        migrations.AlterField(
            model_name='execmember',
            name='name',
            field=models.ForeignKey(help_text='Select Member Name', on_delete=django.db.models.deletion.CASCADE, to='member.Person'),
        ),
        migrations.AlterUniqueTogether(
            name='execmember',
            unique_together=set([('committe_period', 'rank')]),
        ),
    ]
