# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20161116_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='execmember',
            options={'ordering': ['-committe_period', '-rank']},
        ),
        migrations.AlterField(
            model_name='constitution',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
