# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20161116_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
