# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20161117_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
