# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 03:33
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import member.file_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=33)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_for_month='pub_date')),
                ('text', models.TextField()),
                ('docfile', models.FileField(blank=True, null=True, upload_to='news/%Y/%m/%d/', validators=[member.file_validators.validate_file_extension, member.file_validators.file_size])),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='date published')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('events', models.ManyToManyField(blank=True, related_name='blog_posts', to='member.Event')),
                ('tags', models.ManyToManyField(blank=True, related_name='blog_posts', to='member.Tag')),
            ],
            options={
                'ordering': ['-pub_date', 'title'],
                'get_latest_by': 'pub_date',
                'verbose_name': 'blog post',
                'permissions': (('view_future_post', 'Can view unpublished Post'),),
            },
        ),
        migrations.AlterIndexTogether(
            name='post',
            index_together=set([('slug', 'pub_date')]),
        ),
    ]
